### ISSUE TITLE
Helm chart: "dotnet es-replicator.dll": executable file not found in $PATH: unknown

### ISSUE THREAD

**Issue by TomMante** [EventStore/replicator#46]
**Describe the bug**
Trying to deploy es-replicator on a kubernetes cluster to replicate from a GCP vm to a EventstoreCloud cluster. 
And the pod fails to start and goes into CrashLoopBackOff

**To Reproduce**
Follow the guide on how to setup helm chart and create a values.yml to configure the replicator.
run:
`helm install es-replicator es-replicator/es-replicator -f values.yml -n es-replicator`

Error and the pod won't start.

**Expected behavior**
Pod is started and replication process is starting.

**Actual behavior**
Pod is not started and I get this message:
```
Events:
  Type     Reason                  Age                From                     Message
  ----     ------                  ----               ----                     -------
  Warning  FailedScheduling        47s (x2 over 47s)  default-scheduler        0/4 nodes are available: 4 pod has unbound immediate PersistentVolumeClaims.
  Normal   Scheduled               44s                default-scheduler        Successfully assigned es-replicator/es-replicator-0 to gke-application-staging-application-staging-6ee9e541-dqq3
  Normal   SuccessfulAttachVolume  39s                attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-2c7daa6f-4a3a-4957-8833-c83b91a3c024"
  Normal   Pulled                  28s                kubelet                  Successfully pulled image "eventstore/replicator:0.4.3" in 6.169007195s
  Normal   Pulled                  25s                kubelet                  Successfully pulled image "eventstore/replicator:0.4.3" in 1.182363237s
  Normal   Pulling                 3s (x3 over 34s)   kubelet                  Pulling image "eventstore/replicator:0.4.3"
  Normal   Created                 2s (x3 over 27s)   kubelet                  Created container es-replicator
  Warning  Failed                  2s (x3 over 27s)   kubelet                  Error: failed to create containerd task: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "dotnet es-replicator.dll": executable file not found in $PATH: unknown
  Warning  BackOff                 2s (x4 over 25s)   kubelet                  Back-off restarting failed container
  Normal   Pulled                  2s                 kubelet                  Successfully pulled image "eventstore/replicator:0.4.3" in 1.178010697s
```

**EventStore details**
- Target eventstore 21.10, m8 3node cluster.

**Additional context**
This happened to be with both "latest" and 0.4.3 tags. I am currently trying to rollback to an older tag version and see if it helps.

**Comment by alexeyzimarev** [comment]
Sorry about this. Rolling back would definitely help, but remember to use the older Helm chart version. The latest chart points to Docker Hub, and the previous version is in GCR.

I will have to look at it asap.

**Comment by alexeyzimarev** [comment]
It was a stupid mistake in the entrypoint definition. I just pushed 0.4.4 which should fix it. I will do more black-box tests to prevent this from happening.

**Comment by TomMante** [comment]
Thank you! 
Quick dummy question (I am no expert with helm).
But I have the same issue with --version 0.4.0, because it seems like that chart is pointing to "latest" and on
`eu.gcr.io/esc-platform-advocacy/eventstore/replicator:latest`
"latest" is actually 0.4.2. So could you tell me how to tell the chart to use 0.4.0 image instead?

**Comment by alexeyzimarev** [comment]
The latest in GCR is 0.4.2. From 4.3.2 (which has this bug) onwards it is Docker Hub. the latest Helm chart has a fixed version. Helm chart 0.4.4 points to 0.4.4 replicator container image.

**Comment by alexeyzimarev** [comment]
I removed 0.4.2 image from GCR and tagged 0.4.1 as `latest` there, so it should work.

**Comment by TomMante** [comment]
yes, it has now started to run the replication.

Thank you very much!

**Comment by alexeyzimarev** [comment]
Should be fine also with 0.4.5
