### ISSUE TITLE
Dashboard won't run

### ISSUE THREAD

**Issue by poostwoud** [EventStore/replicator#57]
**Describe the bug**
InvalidOperationException: The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request.

**To Reproduce**
1. Download and extract archive;
2. Open solution in VS2022;
3. Run `yarn install` from "Package Manager Console"
4. Run es-replicator
5. Navigate to `localhost:5000`

**Expected behavior**
Dashboard showing the current replication metrics.

**Actual behavior**
InvalidOperationException: The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request.

**Config/Logs/Screenshots**
No changes made to the download.

**Additional context**
The replication itself seems to work. The checkpoint file is being modified. It seems like the routing defined is not getting picked up. I've looked for the exception message shown, however this brought me in the wrong direction. I think I have to look into the routing. I've tried to create some test projects for Vue, however I can't find any differences in the typescript files, but I can't seem to find an example with the projects startup.cs as well.

It must be something stupid. Any ideas?

Cheers,

Peter

**Comment by alexeyzimarev** [comment]
I think the web app doesn't start when in debug mode. You can just go to the `ClientApp` directory and run `yarn serve`.

**Comment by poostwoud** [comment]
Thanks for the tip in the right direction. This is indeed the issue. We've setup an Ubuntu wsl and ran the frontend from there and the backend from VS2022. This works perfectly.
