### ISSUE TITLE
Support for metadata changes in HTTP transformations

### ISSUE THREAD

**Issue by benji24290** [EventStore/replicator#79]
**Is your feature request related to a problem? Please describe.** 
Unlike the JS transformations, the HTTP transformations don't support metadata transformations.

**Describe the solution you'd like**
Use the same interface as the JS transformations:
Stream - original stream name
EventType - original event type
Data - event payload as an object
Metadata - event metadata as an object

## **Describe alternatives you've considered**

**Additional context**
[https://replicator.eventstore.org/docs/features/transforms/http/](https://replicator.eventstore.org/docs/features/transforms/http/)
[https://replicator.eventstore.org/docs/features/transforms/js/](https://replicator.eventstore.org/docs/features/transforms/js/)

<sub>[DEV-272](https://linear.app/eventstore/issue/DEV-272/support-for-metadata-changes-in-http-transformations)</sub>

**Comment by alexeyzimarev** [comment]
We have to keep the name `Payload` for backwards compatibility.
